version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./.envs/.local/.localenv
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:alpine3.18
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ultrapassword
      - POSTGRES_DB=musicdb

  redis:
    image: redis:7.0.12
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  db:
  redis:

