version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./.envs/.local/.env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:alpine3.18
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ultrapassword
      - POSTGRES_DB=musicdb

volumes:
  db:

