"""nullable album_id

Revision ID: 05220f32d603
Revises: 3133b1735067
Create Date: 2023-07-12 09:54:34.220829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05220f32d603'
down_revision = '3133b1735067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
