"""datetime to date

Revision ID: 3133b1735067
Revises: 67994bb283ca
Create Date: 2023-07-08 15:31:03.963107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3133b1735067'
down_revision = '67994bb283ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('year_of_birth',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('year_of_birth',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
