"""user admin

Revision ID: 67994bb283ca
Revises: 1373a46b6616
Create Date: 2023-07-05 13:31:44.688309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67994bb283ca'
down_revision = '1373a46b6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
